import '@ant-design/v5-patch-for-react-19'

import '@/styles/reset.scss'
import 'material-symbols'
import '@/styles/index.scss'
import '@/styles/global.scss'

import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Be_Vietnam_Pro } from 'next/font/google'
import type { Metadata } from 'next'
import { Wrapper } from '@/app/_components/wrapper'
import { ReactNode } from "react";

const beVietNamePro = Be_Vietnam_Pro({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['vietnamese'],
})

export const metadata: Metadata = {
  title: 'Rizz Dashboard', description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode


}>) {
  return (<html lang="vi">
  <head>
    <link
      rel="icon"
      href="/asset/logo/favicon.ico"
    />
  </head>
  <body className={`${beVietNamePro.className}  `}>
  <AntdRegistry>
    <Wrapper>{children}</Wrapper>
  </AntdRegistry>
  </body>
  </html>)
}
