import './globals.css'

import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Be_Vietnam_Pro } from 'next/font/google'
import type { Metadata } from 'next'

const beVietNamePro = Be_Vietnam_Pro({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['vietnamese'],
})

export const metadata: Metadata = {
  title: 'Rizz Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/assest/logo/favicon.ico"
        />
      </head>
      <body className={`${beVietNamePro.className}  `}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  )
}
