export const ROUTERS = {
  home: '/',
  media: '/media',
  products: '/products',
  productDetail: '/products/product-detail',
  productCategory: '/product-category',
  posts: '/posts',
  postDetail: '/posts/post-detail',
  orders: '/orders',
  orderDetail: '/orders/order-detail',
  users: '/users',
  userDetail: '/users/user-detail',
  reviews: '/reviews',
  reviewDetail: '/reviews/review-detail',
  comments: '/comments',
  commentDetail: '/comments/comment-detail',
}
